### PR TITLE
List to  event to make side bar taps work in mobile safari/iOS, relev…

### PR DESCRIPTION
**Pull request by swingley**
…ant to #29.

There are a number of discussions around this issue in various places online. I found this fix via [David Walsh's iOS Mobile Safari Hover Menu Fix post](http://davidwalsh.name/ios-hover-menu-fix).

### CODE REVIEW

**Comment by swingley** [comment]
While this works to trigger click events with a single tap in mobile safari, it makes it impossible to scroll the side bar so I'm looking for a different solution.

**Comment by swingley** [comment]
Finally figured out that the [side bar mouseover event listener](https://github.com/bmcbride/bootleaf/blob/master/assets/js/app.js#L12-L14) was the culprit. My work around is to check for touch-support via:

```js
if ( !("ontouchstart" in window) ) {
  // attach mouseover listener for highlighting
}
```

@bmcbride Do you want a PR for this?

**Comment by bmcbride** [comment]
Sure! Thanks for looking into this.

**Comment by swingley** [comment]
@bmcbride np, made a new PR

**Pull request closed without merging**
